pipeline {
    agent any

    tools {
        nodejs 'NodeJS 24' // Use the NodeJS configuration from Jenkins
    }

    environment {
        CI = 'true'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/blessador/simple-nodejs-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                powershell 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                powershell 'npm test'
            }
        }

        stage('Build') {
            steps {
                powershell 'npm run build'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Deploy script or commands can be added here
                    powershell 'Write-Host "Deploying the application..."'
                    
                    // Start the Node.js server in background
                    powershell 'Start-Process -NoNewWindow -FilePath "node" -ArgumentList "server.js"'
                    
                    sleep 30
                    
                    // Stop the Node.js processes
                    powershell 'Stop-Process -Name "node" -Force -ErrorAction SilentlyContinue'
                }
            }
        }
    } // end of Stages

    post {
        always {
            echo 'Cleaning up...'
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
